name: url_builder
description: "A utility class to construct and safely build URLs in a chainable way."
version: 1.0.0
homepage:
publish_to: 'https://pub.dev'
homepage: https://github.com/yourusername/my_package
repository: https://github.com/yourusername/my_package
issue_tracker: https://github.com/yourusername/my_package/issues

example: example/url_builder_example.dart
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


