name: url_builder_enhanced
description: "A utility class to construct and safely build URLs in a chainable way."
version: 1.0.0
repository: https://github.com/anugrahkora/url_builder
issue_tracker: https://github.com/anugrahkora/url_builder/issues
license: MIT

example: example/url_builder_example.dart
environment:
  flutter: ">=3.0.0"
  sdk: "^3.5.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


